version: '2'
services: 
  pg_db_1:
    build:
      context: ./ubuntu_01/
    container_name: pg_db_1
    expose: 
      - 5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
  pg_db_2:
    build:
      context: ./ubuntu_02/
    container_name: pg_db_2
    expose: 
      - 5432